service: contact-form-api

custom:
  secrets: ${file(serverless.secrets.json)}

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.secrets.NODE_ENV}
  region: 'us-east-1'
  profile: ${self:custom.secrets.PROFILE}
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    EMAIL: ${self:custom.secrets.EMAIL}
    DOMAIN: ${self:custom.secrets.DOMAIN}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"

functions:
  send:
    handler: contact.send
    events:
      - http:
          path: email/send
          method: post
          cors: true
  unlock:
    handler: unlock.handler
    events:
      - http:
          path: unlock/{file}
          method: get
          cors: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "s3:*"
        Resource: "arn:aws:s3:::carmanualsorgcontent/*"